config/routes.rb
Rails.application.routes.draw do
  # default_url_options :host => "example.com"
  devise_for :users
  devise_scope :user do
    root 'devise/sessions#new'
  end
  resources :users
  resources :request_approvals
  post '/request_approvals/:id/approve', to: 'request_approvals#approve'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request_approval.rb
# model class  for RequestApproval
class RequestApproval < ApplicationRecord
  validates_presence_of :name, :description
  belongs_to :approver, class_name: 'User'
  belongs_to :requester, class_name: 'User'

  scope :to_be_approved, ->(user) { where 'approver_id = ? AND approved_status = ?', user, 'NOT APPROVED' }

  def mark_as_approved
    self.approved_status = 'APPROVED'
    self.approved_at = Time.now
  end
  class << self
    def fetch_pending_requests
      where(approved_at: nil)
    end

    def request_daily_mails(requests)
      reuests_hash = requests.group_by(&:approver_id)
      reuests_hash.each do |_key, value|
        RequestMailer.request_pending(value).deliver_later
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    request_approvals_path
  end
end

app/controllers/request_approvals_controller.rb
# controller which deals request and approval
class RequestApprovalsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_request, only: [:edit, :update, :destroy, :show, :approve]

  def new
    @request_approval = RequestApproval.new
    @users = User.all
  end

  def create
    @request_approval = RequestApproval.new(request_params)
    @request_approval.requester = current_user
    if @request_approval.save
      flash[:success] = 'Request submitted successfully'
      RequestMailer.request_received(current_user,
                                     @request_approval).deliver_later
      redirect_to @request_approval
    else
      flash[:error] = 'error on request creation'
      render 'new'
    end
  end

  def show
  end

  def update
  end

  def index
    @requests_for_approvals = RequestApproval.to_be_approved(current_user)
  end

  def edit
  end

  def destroy
  end

  def approve
    @request_detail.mark_as_approved
    if @request_detail.save!
      flash[:success] = 'Request Approved successfully'
      redirect_to request_approvals_path
    else
      flash[:error] = 'Error on Approval'
      redirect_to @request_detail
    end
  end

  private

  def find_request
    @request_detail = RequestApproval.find(params[:id])
  end

  def request_params
    params.require(:request_approval).permit(:name, :description, :approver_id)
  end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/request_approvals_helper.rb
module RequestApprovalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Approval System', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'New Approvals ', new_request_approval_path %></li>
        <li><a href="#"> Pending Approvals</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- to be fixed  -->
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path%></li>
          <li><%= link_to 'SignUp', new_user_registration_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApprovalSystem</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/navbar'%>
  <div class="container">
    <div class= 'row'>
      <%flash.each do |name, msg| %>
        <% if name == 'notice' %>
          <%= content_tag :div, msg, class: "alert alert-info" %>
        <% elsif name == 'success' %>
          <%= content_tag :div, msg, class: "alert alert-success" %>
        <%else%>
          <%= content_tag :div, msg, class: "alert alert-danger" %>
        <% end%>
      <% end %>
    </div>
    <div class="row">
      <body>
        <%= yield %>
      </body>
    </div>
  </div>
</html>

app/views/request_approvals/_form.html.erb
<div class="container">
  <%= simple_form_for @request_approval do |f| %>
    <%= f.input :name, label: 'Request title' %>
    <%= f.input :description, label: 'Request description' %>
    <%=f.label 'Approver name'%>
    <%= f.select(:approver_id, options_from_collection_for_select(@users, :id, :email),
                 prompt: 'Please Select')%> </br>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/request_approvals/index.html.erb
<div>
Pending Tasks:
--------------
  <% @requests_for_approvals.each do |request|%>
    <%= link_to 'request.name', request_approval_path(request)%>
  <% end %>
</div>

app/views/request_approvals/new.html.erb
<h3>Request Page</h3>
<%= render 'form'%>

app/views/request_approvals/show.html.erb
<div class="form-group">
  <p> name<%= @request_detail.name %></p>
  <p>description <%= @request_detail.description%></p>
  <p>requested_by <%= @request_detail.requester.email%></p>
  <p>approved_by <%= @request_detail.approver.email%></p>
</div>
<div>
  <%= button_to 'approve', action: "approve"%>
</div>

app/views/users/index.html.erb
<h3>Index Page</h3>

app/views/users/show.html.erb
<h2>welcome</h2><%=@user.email%>